analyzer:
  exclude:
    - build/**
    - android/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false # Permitted for debug logging in development
    use_key_in_widget_constructors: true
