-- V16: Support Centers, Krishi Vigyan Kendras (KVK), Soil Labs & FPO Hubs

CREATE TABLE IF NOT EXISTS support_centers (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    center_type VARCHAR(50) NOT NULL,
    badge VARCHAR(100),
    designation VARCHAR(255),
    department VARCHAR(255),
    district VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    address TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    rating VARCHAR(10) DEFAULT '4.8',
    phone VARCHAR(50),
    toll_free VARCHAR(50),
    operating_hours VARCHAR(100),
    services TEXT,
    in_charge VARCHAR(255),
    verified BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_support_centers_type ON support_centers(center_type);
CREATE INDEX IF NOT EXISTS idx_support_centers_district ON support_centers(district);
CREATE INDEX IF NOT EXISTS idx_support_centers_coords ON support_centers(latitude, longitude);

-- Seed initial verified KVKs, Soil Labs, Agronomists and Helplines
INSERT INTO support_centers (
    name, center_type, badge, designation, department, district, state, address, latitude, longitude, rating, phone, toll_free, operating_hours, services, in_charge, verified
) VALUES
(
    'Krishi Vigyan Kendra (ICAR-KVK Research Station)',
    'GOVT_KVK',
    'ICAR Govt Research Station',
    'District Agricultural Extension & Research Hub',
    'Indian Council of Agricultural Research (ICAR)',
    'Nashik',
    'Maharashtra',
    'Panchavati, Dindori Road, Nashik Cluster, Maharashtra 422003',
    20.0384,
    73.8052,
    '4.9',
    '+91 253 2530182',
    '1800-180-1551',
    'Mon - Sat: 09:30 AM - 05:30 PM',
    'Soil Health Testing, Certified Seed Distribution, Free Crop Pathology Diagnosis, PM-Kisan Desk',
    'Dr. S. K. Jadhav (Chief Agronomist & Extension Lead)',
    TRUE
),
(
    'ICAR-KVK Ranchi (Divyayan KVK)',
    'GOVT_KVK',
    'ICAR Govt Research Station',
    'Divyayan Krishi Vigyan Kendra & Agro Training Center',
    'Ramakrishna Mission Ashram & ICAR',
    'Ranchi',
    'Jharkhand',
    'Morabadi, Ranchi, Jharkhand 834008',
    23.3850,
    85.3260,
    '4.9',
    '+91 651 2551008',
    '1800-180-1551',
    'Mon - Sat: 09:00 AM - 05:00 PM',
    'Mushroom Cultivation Training, Organic Farming Certification, Soil Fertility Profiling, Seed Multiplication',
    'Dr. A. K. Singh (Principal Scientist)',
    TRUE
),
(
    'Dr. Vikram Mane (Ph.D. Plant Pathology)',
    'AGRONOMIST',
    'Certified Senior Agronomist',
    'Horticulture & Pathology Specialist',
    'State Agricultural Extension Panel & AgroSciences',
    'Nashik',
    'Maharashtra',
    'Pimpalgaon Baswant APMC Cluster, Nashik 422209',
    20.1652,
    73.9878,
    '5.0',
    '+91 98224 81732',
    NULL,
    'Daily: 08:00 AM - 07:00 PM',
    'Tomato & Chilli Blight Remediation, Spray Calibration & PHI, Organic Bio-Input Regimes',
    'Lead Crop Consultant',
    TRUE
),
(
    'District Central Soil & Water Testing Laboratory',
    'SOIL_LAB',
    'Govt NABL Accredited',
    'Certified Nutrient & Micro-Nutrient Laboratory',
    'Department of Agriculture, Govt of Maharashtra',
    'Nashik',
    'Maharashtra',
    'Krishi Bhavan Campus, Old Agra Road, Nashik 422002',
    19.9975,
    73.7898,
    '4.8',
    '+91 253 2574921',
    '1800-233-0244',
    'Mon - Fri: 10:00 AM - 05:00 PM',
    'NPK & Micronutrient Profiling, EC & pH Salinity Testing, Subsidized Soil Health Cards',
    'A. R. Patil (Quality Control Officer)',
    TRUE
),
(
    'Ranchi State Soil Testing Laboratory',
    'SOIL_LAB',
    'Govt NABL Accredited',
    'Jharkhand State Agricultural Testing Facility',
    'Department of Agriculture, Govt of Jharkhand',
    'Ranchi',
    'Jharkhand',
    'Kanke Road, Near Birsa Agricultural University, Ranchi 834006',
    23.4358,
    85.3182,
    '4.7',
    '+91 651 2450832',
    '1800-345-6540',
    'Mon - Fri: 10:00 AM - 05:00 PM',
    'Micro-Nutrient Assay, Heavy Metal Screening, Soil pH & Organic Carbon Analysis',
    'Dr. Sunita Murmu (Senior Chemist)',
    TRUE
),
(
    'National Kisan Call Center (24x7 Helpline)',
    'HELPLINE',
    'National Toll-Free 24x7',
    'Free Agronomic Advice in Local Languages',
    'Ministry of Agriculture & Farmers Welfare, GoI',
    'All India',
    'National',
    'Krishi Bhawan, Dr. Rajendra Prasad Road, New Delhi 110001',
    28.6186,
    77.2155,
    '4.9',
    '1800-180-1551',
    '1800-180-1551',
    '24 Hours / 7 Days a Week',
    'Emergency Pest Attack Advisory, MSP & Market Scheme Info, Weather Disaster Warnings',
    'Senior Agronomy Officers Panel',
    TRUE
),
(
    'Sahyadri Farmers Producer Co. (FPO Hub)',
    'FPO_HUB',
    'Certified Farmer Producer Org',
    'Bulk Aggregation & Cold Storage Hub',
    'Ministry of Corporate Affairs & NABARD FPO Program',
    'Nashik',
    'Maharashtra',
    'Survey No. 314, Mohadi, Dindori Road, Nashik 422207',
    20.1412,
    73.8450,
    '4.9',
    '+91 2557 279100',
    NULL,
    'Mon - Sun: 07:00 AM - 08:00 PM',
    'Direct Buyer Aggregation, Pre-Cooling & Cold Chain, Export Quality Grading, Collective Input Buying',
    'Vilas Shinde (FPO Director)',
    TRUE
);
